### ISSUE TITLE
Incorrect private key used for signing in integration tests

### ISSUE THREAD

**Issue by jurchiks** [isign/isign-sdk-php#1]
https://github.com/isign/isign-sdk-php/blob/master/tests/Integration/ScLoginTest.php#L32
should be using:
https://github.com/isign/isign-sdk-php/blob/master/phpunit.xml.dist#L26
as it is currently, but:
https://github.com/isign/isign-sdk-php/blob/master/tests/Integration/ScSignTest.php#L49
should be using:
https://github.com/isign/isign-sdk-php/blob/master/phpunit.xml.dist#L28
Currently they both use the same login private key.

or am I getting it wrong?

**Comment by kuusas** [comment]
Good catch! Thanks! Will be fixed in upcoming release.

**Comment by kuusas** [comment]
Fixed with 4a1298370d8e041594dceb3602469003b3ae65b1
