### ISSUE TITLE
API changes?

### ISSUE THREAD

**Issue by jurchiks** [isign/isign-sdk-php#2]
We recently received an e-mail about API changes:

> We just updated our APIs for Smart-ID regarding Document Signing - https://developers.isign.io/#_sc_login
> Identification part is also coming soon, most likely next week.

That was on February 19.
What exactly changed and if anything did, when will the SDK be updated?

**Comment by podolskis** [comment]
Smart-ID signing and identification is rolled out to developers sandbox, for testing purposes. You can give it a try with simple php demo script right now - https://github.com/isign/php-example.

SDK will be updated latter then Smart-ID is rolled out to production.

**Comment by jurchiks** [comment]
I see, thanks.
